const Sequelize=require('sequelize');
const sequelize=require('../database/connect');


const detailFeedbackModel=sequelize.define('detailFeedback',{
    id:{
        type:Sequelize.INTEGER,
        autoIncrement:true,
        primaryKey:true,
    },
    name:{
        type:Sequelize.STRING
    },
    company:{
        type:Sequelize.STRING
    },
    role:{
        type:Sequelize.STRING
    },
    date:{
        type:Sequelize.STRING
    },
    time:{
        type:Sequelize.STRING
    },
    language:{
        type:Sequelize.STRING
    },
    priorExperience:{
        type:Sequelize.STRING
    },
    projects:{
        type:Sequelize.STRING
    },
    techStack:{
        type:Sequelize.STRING
    },
    dsaQuestion1:{
        type:Sequelize.STRING
    },
    dsaAnswer1:{
        type:Sequelize.STRING
    },
    dsaQuestion2:{
        type:Sequelize.STRING
    },
    dsaAnswer2:{
        type:Sequelize.STRING
    },
    osQuestion1:{
        type:Sequelize.STRING
    },
    osAnswer1:{
        type:Sequelize.STRING
    },
    osQuestion2:{
        type:Sequelize.STRING
    },
    osAnswer2:{
        type:Sequelize.STRING
    },
    dbmsQuestion1:{
        type:Sequelize.STRING
    },
    dbmsAnswer1:{
        type:Sequelize.STRING
    },
    dbmsQuestion2:{
        type:Sequelize.STRING
    },
    dbmsAnswer2:{
        type:Sequelize.STRING
    },
    uniqueId:{
        type:Sequelize.STRING       
    }
});

module.exports=detailFeedbackModel;