const Sequelize=require('sequelize');
const sequelize=require('../database/connect');

const realTimeFeedbackModel=sequelize.define(' realTimeFeedback',{
    id:{
        type:Sequelize.INTEGER,
        autoIncrement:true,
        primaryKey:true,
    },
    studentId:{
        type:Sequelize.STRING
    },
    name:{
        type:Sequelize.STRING
    },
    role:{
        type:Sequelize.STRING
    },
    date:{
        type:Sequelize.STRING
    },
    time:{
        type:Sequelize.STRING
    },
    codingLanguage:{
        type:Sequelize.STRING
    },
    communication:{
        type:Sequelize.STRING
    },
    email:{
        type:Sequelize.STRING
    },
    thinkingSpeed:{
        type:Sequelize.STRING
    },
    codingSpeed:{
        type:Sequelize.STRING
    },
    codeQuality:{
        type:Sequelize.STRING
    },
    concentration:{
        type:Sequelize.STRING
    },
    os:{
        type:Sequelize.STRING
    },
    dbms:{
        type:Sequelize.STRING
    },
    dataStructure:{
        type:Sequelize.STRING
    },
    algorithm:{
        type:Sequelize.STRING
    },
    apptitude:{
        type:Sequelize.STRING
    },
    personalityAndBehaviour:{
        type:Sequelize.STRING
    },
    projectAndResume:{
        type:Sequelize.STRING
    },
    overallAnalysis:{
        type:Sequelize.STRING
    },
    averageRating:{
        type:Sequelize.STRING
    },
    uniqueId:{
        type:Sequelize.STRING
    }
});

module.exports=realTimeFeedbackModel;